#!/usr/bin/env bash

okcUrl='https://www.okcupid.com/login'
cookieDir="${OKC_PATH}/.okc_cookies"
cookies='cookies.txt'

[ -d "$cookieDir" ] || mkdir "$cookieDir"

# prime cookie jar
curl -sc ${cookieDir}/$cookies -o /dev/null $okcUrl

# log in and update cookie jar
curl -b ${cookieDir}/$cookies -c ${cookieDir}/$cookies -d 'dest=/profile?' -d "username=${OKC_USER}" -d "password=${OKC_PASS}" -Ls $okcUrl | okcp

# remove empty cookie jar
rm ${cookieDir}/$cookies
