#!/usr/bin/env bash

set -e

okcliUrl='https://www.okcupid.com/login'
cookieDir="${OKCLI_PATH}/.okcli_cookies"
cookies='cookies.txt'

[ -d "$cookieDir" ] || mkdir "$cookieDir"

# prime cookie jar
curl -sc ${cookieDir}/$cookies -o /dev/null $okcliUrl

# log in,  update cookie jar, and send page to okclistats
curl -b ${cookieDir}/$cookies -c ${cookieDir}/$cookies -d 'dest=/profile?' -d "username=${OKCLI_USER}" -d "password=${OKCLI_PASS}" -Ls $okcliUrl | okstats

# remove empty cookie jar
rm ${cookieDir}/$cookies
