#!/usr/bin/env bash

set -e

okcli_url='https://www.okcupid.com/login'
cookie_dir="${OKCLI_PATH}/.okcli_cookies"
cookies='cookies.txt'

[ -d "$cookie_dir" ] || mkdir "$cookie_dir"

# prime the cookie jar
curl -sc ${cookie_dir}/$cookies -o /dev/null $okcli_url

# log in,  update cookie jar, and send page to okclistats
curl -b ${cookie_dir}/$cookies -c ${cookie_dir}/$cookies -d 'dest=/profile?' -d "username=${OKCLI_USER}" -d "password=${OKCLI_PASS}" -Ls $okcli_url | okstats

# remove empty cookie jar
rm ${cookie_dir}/$cookies
