#!/usr/bin/env awk -f

BEGIN{
  statsRegex     = "Navigation\.init"
  properties[1]  = "mailbox"
  properties[2]  = "visitors"
  properties[3]  = "ratings"
}

{
  if($0 ~ statsRegex)
  {
    for(key in properties)
    {
      property        = properties[key]
      regex           = property"[^:]*:[^{]*\{\s*[^c]+?count[^:]+:\s*.[0-9]+"

      if(match($0,regex))
      {
        str = substr($0,RSTART,RLENGTH)
        if(match(str,/[0-9]+$/))
        {

          if(property ~ /^mailbox$/)
          {
            property = "messages"
          }

          if(property ~ /^ratings$/)
          {
            property = "likes"
          }

          label = "\033[38;5;27m"toupper(substr(property,1,1))substr(property,2)"\033[0m"
          value = substr(str,RSTART,RLENGTH)

          label_length = length(label)

          if(max_label_length < label_length)
          {
            max_label_length = label_length
          }

          if(value + 0 > 0)
          {
            value = "\033[38;5;198m"value"\033[0m"
          }

          printf "%"max_label_length"s %s\n",label,value
        }
      }
    }

    print ""
    FS = "<\/a>[^<]*</li>"
    next
  }
}
